In [1]:
import json
import pandas as pd
import networkx as nx
import collections
import torch

In [14]:
G = nx.MultiDiGraph()

In [15]:
G.add_node(1)

In [16]:
G.add_node(2)

In [24]:
G.add_edge(1,2, key="lol",t=0)

'lol'

In [18]:
G.add_edge(1,2,t=1)

1

In [25]:
G.edges[1,2,"lol"]

{'t': 0}

In [3]:
from torch_geometric.datasets import Planetoid

dataset = Planetoid(root='/tmp/Cora', name='Cora')

In [13]:
dataset

Cora()

In [33]:
dataset[0].y

tensor([3, 4, 4,  ..., 3, 3, 3])

In [12]:
dataset[0].x[2707]

tensor([0., 0., 0.,  ..., 0., 0., 0.])

In [9]:
dataset[0]

Data(x=[2708, 1433], edge_index=[2, 10556], y=[2708], train_mask=[2708], val_mask=[2708], test_mask=[2708])

In [24]:
model = torch.nn.LSTM(input_size=1, hidden_size=10, num_layers=1)

In [25]:
x = torch.randn(3, 1)

In [27]:
output = model(x)

In [32]:
output

(tensor([[-0.0479,  0.0398,  0.0071,  0.1052, -0.0073,  0.0414, -0.0541,  0.0067,
           0.1058, -0.1488],
         [-0.0417,  0.0077, -0.0151,  0.0620,  0.0090,  0.0742, -0.0126, -0.1539,
           0.1614, -0.0683],
         [-0.0471,  0.0189, -0.0029,  0.0794,  0.0111,  0.0999, -0.0527, -0.1246,
           0.1717, -0.1077]], grad_fn=<SqueezeBackward1>),
 (tensor([[-0.0471,  0.0189, -0.0029,  0.0794,  0.0111,  0.0999, -0.0527, -0.1246,
            0.1717, -0.1077]], grad_fn=<SqueezeBackward1>),
  tensor([[-0.1196,  0.0492, -0.0052,  0.1432,  0.0259,  0.2555, -0.0944, -0.2565,
            0.3807, -0.2751]], grad_fn=<SqueezeBackward1>)))

In [29]:
x, (h, c) = output

In [31]:
h

tensor([[-0.0471,  0.0189, -0.0029,  0.0794,  0.0111,  0.0999, -0.0527, -0.1246,
          0.1717, -0.1077]], grad_fn=<SqueezeBackward1>)